### ISSUE TITLE
Package does not work with cmake find_package

### ISSUE THREAD

**Issue by kylemacfarlan** [conan-community/conan-pybind11#3]
The package does not seem to be setup to work with the usual cmake find_package idiom. For an example of how I think it should work, you can see this minimal example here: https://github.com/kylemacfarlan/conan_pybind11. 

running cmake with this repo produces the following message:
" By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one."

**Comment by memsharded** [comment]
Thanks for pointing this out! I hadn't realized that the find cmake provided by pybind11 had this functionality. 

I have restored the CMake and ``cmake.install()`` functionality and now the cmake scripts are there. Added your CMake example to the test_package tests, with minimal changes, and CI is green.

Please check and tell me, this library is almost ready for inclusion in conan-center.

**Comment by kylemacfarlan** [comment]
The fix works great! Thanks for doing that so quickly.
